version: 4b712853
tdp:
  general:
    profile: default
    sched: default
gamemode:
  power:
    hibernate_auto: default
  gamescope:
    steamui_halfhz: default
    dpms: default
updates:
  bootc:
    image: bazzite-deck-nvidia:stable
    stage:
      incompatible:
        error: default
    status: ''
shortcuts:
  controller:
    xbox_y: default
    xbox_b: default
    xbox_a: default
    xbox_x: default
    allow_select: default
  touchscreen:
    bottom: default
    right_top: default
    right_bottom: default
    left_top: default
    left_bottom: default
    top: default
    orientation:
      mode: default
      manual:
        dmi: default
        portrait: default
        flip_x: default
        flip_y: default
  keyboard:
    meta_press: default
    meta_hold: default
    ctrl_3: default
    ctrl_4: default
debug:
  reports:
    boot: default
    status: default
hhd:
  settings:
    language: default
    theme: default
    bootc_steamui: default
    powerbuttond: false
  http:
    localhost: default
    token: default

#
#     _______   _______    ______  
#    /    /  ╲╲/    /  ╲╲_/      ╲╲
#   /        //        //        //
#  /         /         /         / 
#  ╲___/____/╲___/____/╲________/  
#  
# Handheld Daemon State Config
#
# This file contains plugin software-only configuration that will be retained
# across reboots. You may edit this file in lueu of using a frontend.
# This header is on the bottom to make editing easier with e.g., nano.
#
# Parameters that are stored in hardware (TDP, RGB colors, etc) and
# risky parameters that might cause instability and should be reset
# across sessions are not part of this file.
# Use profiles to apply changes to these settings.
#
# Persisted (software) parameters are marked by having a default value.
# Non-persisted/hardware parameters do not have a default value.
#
# This file and comments are autogenerated. Your comments will be discarded
# during configuration changes. Parameters with the value `default` are
# ignored and are meant as a template for you to change them.
#
# - CONFIGURATION PARAMETERS
#
# ┌> tdp.general
# │ 
# │ *Power*
# │
# │┌> tdp.general.profile
# ││ *Power Profile*
# ││ Allows setting the power profile of the system using Power Profiles Daemon. 
# ││ - options: [power-saver, balanced, performance]
# │└ - default: balanced
# │
# │┌> tdp.general.sched
# ││ *Custom Scheduler*
# ││ Allows attaching a scheduler to the kernel sched_ext. Schedulers need to be 
# ││ installed and kernel needs to support sched_ext. 
# ││ - options: [disabled, scx_lavd, scx_bpfland, scx_rusty]
# └└ - default: disabled
# 
# ┌> gamemode.power
# │ 
# │ *Power*
# │
# │┌> gamemode.power.status
# ││ 
# │└ *Error*
# │
# │┌> gamemode.power.reboot_windows
# ││ *Reboot into Windows*
# ││ Make sure you saved your game progress. 
# │└ - action: Set to True to run.
# │
# │┌> gamemode.power.hibernate
# ││ *Hibernate*
# ││ Saves your progress and powers off the device. 
# │└ - action: Set to True to run.
# │
# │┌> gamemode.power.hibernate_auto
# ││ *Hibernate when device asks and at 5%.*
# ││ Certain devices wake up to force Windows to hibernate. If Linux does not
# ││ they 
# ││ cause issues. Detect and hibernate on thermal events and on 5%
# ││ battery.
# ││  
# ││ - boolean: [False, True]
# └└ - default: True
# 
# ┌> gamemode.display
# │ 
# │ *Display*
# │
# │┌> gamemode.display.touchscreen_disable
# ││ *Disable Touchscreen (Until Restart)*
# │└ - boolean: [False, True]
# │
# │┌> gamemode.display.gestures_disable
# ││ *Disable Touch Gestures (Until Restart)*
# └└ - boolean: [False, True]
# 
# ┌> gamemode.gamescope
# │ 
# │ *Gamescope*
# │
# │┌> gamemode.gamescope.steamui_halfhz
# ││ *Run Steam at 60/72 Hz*
# ││ - boolean: [False, True]
# │└ - default: False
# │
# │┌> gamemode.gamescope.dpms
# ││ *Poweroff screen before sleep*
# ││ - boolean: [False, True]
# └└ - default: True
# 
# ┌> updates.bootc
# │ *System Image*
# │ Manage the currently installed image with bootc. 
# │
# │┌> updates.bootc.steamos-target
# ││ 
# │└ **
# │
# │┌> updates.bootc.steamos-update
# ││ 
# │└ **
# │
# │┌> updates.bootc.image
# ││ *Image*
# │└ - default: bazzite-deck:stable
# │
# │┌> updates.bootc.staged
# ││ 
# │└ *Next*
# │
# │┌> updates.bootc.booted
# ││ 
# │└ *Current*
# │
# │┌> updates.bootc.rollback
# ││ 
# │└ *Previous*
# │
# │┌> updates.bootc.update
# ││ 
# │└ *Update*
# │
# │┌> updates.bootc.stage
# ││ *Update Stage*
# ││ - modes: [ready, ready_rebased, ready_check, ready_updated, ready_reverted, incompatible, loading_cancellable, loading, rebase]
# ││
# ││┌> updates.bootc.stage.ready
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.ready.update
# ││││ *Apply Update*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready.revert
# ││││ *Revert to Previous*
# ││││ Rollback to the previous image. 
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready.rebase
# ││││ *Change Version (Rebase)*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.ready_rebased
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.ready_rebased.update
# ││││ *Remove Pin and Update*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_rebased.revert
# ││││ *Revert to Previous*
# ││││ Rollback to the previous image. 
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_rebased.rebase
# ││││ *Change Branch (Rebase)*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.ready_check
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.ready_check.update
# ││││ *Check for Updates*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_check.revert
# ││││ *Revert to Previous*
# ││││ Rollback to the previous image. 
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_check.rebase
# ││││ *Change Branch (Rebase)*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.ready_updated
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.ready_updated.reboot
# ││││ *Reboot*
# ││││ Reboot to apply the update. Are you sure? 
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_updated.revert
# ││││ *Undo Update*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_updated.update
# ││││ *Check for Updates*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_updated.rebase
# ││││ *Change Branch (Rebase)*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.ready_reverted
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.ready_reverted.reboot
# ││││ *Reboot*
# ││││ Reboot to apply the update. Are you sure? 
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_reverted.revert
# ││││ *Undo Revert*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_reverted.update
# ││││ *Check for Updates*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.ready_reverted.rebase
# ││││ *Choose Version (Rebase)*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.incompatible
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.incompatible.error
# ││││ *Error*
# ││││ - default: Due to layering or custom initramfs, you cannot update from here. You can undo those with the button below.
# │││└ 
# │││
# │││┌> updates.bootc.stage.incompatible.reset
# ││││ *Run rpm-ostree reset*
# ││││ Disable the custom initramfs and remove layers. Your personal data will not be 
# ││││ affected. 
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.loading_cancellable
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.loading_cancellable.progress
# ││││ 
# │││└ **
# │││
# │││┌> updates.bootc.stage.loading_cancellable.cancel
# ││││ *Cancel*
# ││└└ - action: Set to True to run.
# ││
# ││┌> updates.bootc.stage.loading
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.loading.progress
# ││││ 
# ││└└ **
# ││
# ││┌> updates.bootc.stage.rebase
# │││ 
# │││ **
# │││
# │││┌> updates.bootc.stage.rebase.branch
# ││││ *Branch*
# │││└ - options: [stable, testing, unstable]
# │││
# │││┌> updates.bootc.stage.rebase.version
# ││││ 
# │││└ *Version Pin*
# │││
# │││┌> updates.bootc.stage.rebase.version_error
# ││││ 
# │││└ *Error*
# │││
# │││┌> updates.bootc.stage.rebase.apply
# ││││ *Apply*
# │││└ - action: Set to True to run.
# │││
# │││┌> updates.bootc.stage.rebase.cancel
# ││││ *Cancel*
# └└└└ - action: Set to True to run.
# 
# ┌> shortcuts.custom
# │ 
# │ *Device Buttons*
# │
# ┌> shortcuts.controller
# │ 
# │ *External Controllers*
# │
# │┌> shortcuts.controller.xbox_y
# ││ *Xbox + Y*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle, disconnect]
# │└ - default: tdp_cycle
# │
# │┌> shortcuts.controller.xbox_b
# ││ *Xbox + B*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: hhd_expanded
# │
# │┌> shortcuts.controller.xbox_a
# ││ *Xbox + A*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: disabled
# │
# │┌> shortcuts.controller.xbox_x
# ││ *Xbox + X*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: disabled
# │
# │┌> shortcuts.controller.allow_select
# ││ *Use Select as alternative to Xbox*
# ││ - boolean: [False, True]
# └└ - default: True
# 
# ┌> shortcuts.touchscreen
# │ 
# │ *Touchscreen*
# │
# │┌> shortcuts.touchscreen.bottom
# ││ *↑ Swipe Up*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: keyboard
# │
# │┌> shortcuts.touchscreen.right_top
# ││ *← Swipe Right Side (Top)*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: hhd_qam
# │
# │┌> shortcuts.touchscreen.right_bottom
# ││ *← Swipe Right Side (Bottom)*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: steam_qam
# │
# │┌> shortcuts.touchscreen.left_top
# ││ *→ Swipe Left Side (Top)*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: hhd_expanded
# │
# │┌> shortcuts.touchscreen.left_bottom
# ││ *→ Swipe Left Side (Bottom)*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: steam_expanded
# │
# │┌> shortcuts.touchscreen.top
# ││ *↓ Swipe Down*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: disabled
# │
# │┌> shortcuts.touchscreen.orientation
# ││ *Orientation Correction*
# ││ - modes: [auto, manual]
# ││ - default: auto
# ││
# ││┌> shortcuts.touchscreen.orientation.auto
# │││ 
# │││ *Auto*
# │││
# ││┌> shortcuts.touchscreen.orientation.manual
# │││ 
# │││ *Manual*
# │││
# │││┌> shortcuts.touchscreen.orientation.manual.dmi
# ││││ *Device*
# │││└ - default: "Gigabyte Technology Co., Ltd." - "Z390 M GAMING"
# │││
# │││┌> shortcuts.touchscreen.orientation.manual.portrait
# ││││ *Portrait*
# ││││ - boolean: [False, True]
# │││└ - default: False
# │││
# │││┌> shortcuts.touchscreen.orientation.manual.flip_x
# ││││ *Flip Left-Right*
# ││││ - boolean: [False, True]
# │││└ - default: False
# │││
# │││┌> shortcuts.touchscreen.orientation.manual.flip_y
# ││││ *Flip Top-Bottom*
# ││││ - boolean: [False, True]
# └└└└ - default: False
# 
# ┌> shortcuts.keyboard
# │ 
# │ *Keyboard (Gaming Only)*
# │
# │┌> shortcuts.keyboard.meta_press
# ││ *Start (Meta) Press*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: disabled
# │
# │┌> shortcuts.keyboard.meta_hold
# ││ *Start (Meta) Hold*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: disabled
# │
# │┌> shortcuts.keyboard.ctrl_3
# ││ *Ctrl + 3*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# │└ - default: hhd_expanded
# │
# │┌> shortcuts.keyboard.ctrl_4
# ││ *Ctrl + 4*
# ││ - options: [disabled, keyboard, steam_qam, steam_expanded, hhd_qam, hhd_expanded, tdp_cycle]
# └└ - default: hhd_qam
# 
# ┌> debug.reports
# │ 
# │ *Bug Report*
# │
# │┌> debug.reports.url
# ││ 
# │└ *Bug Report Link*
# │
# │┌> debug.reports.error
# ││ 
# │└ *Upload Error*
# │
# │┌> debug.reports.progress
# ││ 
# │└ **
# │
# │┌> debug.reports.submit
# ││ *Submit Report*
# ││ Upload a bug report to paste.centos.org 
# │└ - action: Set to True to run.
# │
# │┌> debug.reports.boot
# ││ *Logs from*
# ││ - options: [current, previous, m2, m3]
# │└ - default: current
# │
# │┌> debug.reports.status
# ││ *None*
# └└ - default: Create a log that will be uploaded to paste.centos.org for 3 days
# 
# ┌> debug.dev
# │ 
# │ *Development Tools*
# │
# │┌> debug.dev.progress
# ││ 
# │└ **
# │
# │┌> debug.dev.error
# ││ 
# │└ **
# │
# │┌> debug.dev.hhd_dev
# ││ *Use HHD Beta Until Restart*
# ││ Switch to the HHD beta channel until you restart. 
# └└ - action: Set to True to run.
# 
# ┌> hhd.settings
# │ 
# │ *Core Settings*
# │
# │┌> hhd.settings.language
# ││ *Language*
# ││ - options: [system, C, zh_CN, zh_TW, pt_BR, ru_RU]
# │└ - default: system
# │
# │┌> hhd.settings.theme
# ││ *Theme*
# ││ Allows changing the theme in the UI. Default is either Diavolo or your 
# ││ distribution's theme. 
# ││ - options: [default, diavolo, ocean, vapor, blood_orange]
# │└ - default: default
# │
# │┌> hhd.settings.reset
# ││ *Reset Settings*
# ││ Resets all Handheld Daemon settings to their default values. 
# │└ - action: Set to True to run.
# │
# │┌> hhd.settings.version
# ││ *Handheld Daemon Version*
# │└ Displays the Handheld Daemon version. 
# │
# │┌> hhd.settings.version_ui
# ││ *Handheld Daemon UI Version*
# │└ Displays the Handheld Daemon version. 
# │
# │┌> hhd.settings.update_error
# ││ 
# │└ *Update Error*
# │
# │┌> hhd.settings.bootc_steamui
# ││ *Show updates in SteamUI*
# ││ - boolean: [False, True]
# │└ - default: True
# │
# │┌> hhd.settings.powerbuttond
# ││ *Steam Powerbutton Handler*
# ││ Enables the Steam Powerbutton handler (responsible for the wink and powerbutton 
# ││ menu). 
# ││ - boolean: [False, True]
# └└ - default: True
# 
# ┌> hhd.http
# │ *API Configuration*
# │ Settings for configuring the http endpoint of HHD. 
# │
# │┌> hhd.http.localhost
# ││ *Limit Access to localhost*
# ││ Sets the API target to '127.0.0.1' instead '0.0.0.0'. 
# ││ - boolean: [False, True]
# │└ - default: True
# │
# │┌> hhd.http.token
# ││ *Use Security token*
# ││ Generates a security token in `~/.config/hhd/token` that is required for 
# ││ authentication. 
# ││ - boolean: [False, True]
# └└ - default: True
# 